/**
 * This file was generated by the JPA Modeler
 */
package br.com.jonyfs.domain;

import br.com.jonyfs.user.User;
import java.io.Serializable;
import javax.persistence.EntityListeners;
import javax.persistence.MappedSuperclass;
import org.springframework.data.jpa.domain.AbstractAuditable;

/**
 * @author jony
 * @param <PK>
 */
@MappedSuperclass
@EntityListeners(org.springframework.data.jpa.domain.support.AuditingEntityListener.class)
public abstract class AuditableEntity<PK extends Serializable> extends AbstractAuditable<User, PK> {

    public static final long serialVersionUID = -3095654078202510664L;


}
