/**
 * This file was generated by the JPA Modeler
 */

package br.com.jonyfs.domain;

import java.io.Serializable;
import javax.persistence.MappedSuperclass;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * @author  jony
 */
@Data
@EqualsAndHashCode(callSuper = true)
@MappedSuperclass
public abstract class BaseEntity extends AuditableEntity<Long> implements Serializable {

}
